version: '3'
services:
  lx-downloader:
    build: .
    container_name: lx-downloader
    restart: unless-stopped
    ports:
      - "5200:5200"
    volumes:
      - /vol1/1000/音乐/downloads:/downloads
    environment:
      - PORT=5200
      - DOWNLOAD_DIR=/downloads
